// apps/sub-react/src/App.tsx

import React from 'react';
import { Button, Card } from 'antd';

function App() {
  return (
    <div className="App" style={{ padding: 20 }}>
      <Card title="React Sub App (Webpack)" bordered={false} style={{ width: 300 }}>
        <p>Technology: React 18 + Webpack 5</p>
        <p>Features: Ant Design</p>
        <Button type="primary">Antd Button</Button>
      </Card>
    </div>
  );
}

export default App;

// apps/sub-vue/src/App.vue

<template>
  <div class="vue-card">
    <a-card title="Vue Sub App (Vite)" style="width: 300px">
      <p>Technology: Vue 3 + Vite + Antd Vue</p>
      <p>Plugin: vite-plugin-qiankun</p>
      <a-button type="primary">Antd Vue Button</a-button>
    </a-card>
  </div>
</template>

<style scoped>
.vue-card {
  padding: 20px;
  background-color: #f0f2f5;
}
</style>
